package model;
// Generated 11-may-2023 20:51:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {


     private Integer idCategoria;
     private double complementoCategoria;
     private double salarioBaseCategoria;
     private String nombreCategoria;
     private Set trabajadors = new HashSet(0);

    public Categorias() {
    }

	
    public Categorias(double complementoCategoria, double salarioBaseCategoria, String nombreCategoria) {
        this.complementoCategoria = complementoCategoria;
        this.salarioBaseCategoria = salarioBaseCategoria;
        this.nombreCategoria = nombreCategoria;
    }
    public Categorias(double complementoCategoria, double salarioBaseCategoria, String nombreCategoria, Set trabajadors) {
       this.complementoCategoria = complementoCategoria;
       this.salarioBaseCategoria = salarioBaseCategoria;
       this.nombreCategoria = nombreCategoria;
       this.trabajadors = trabajadors;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public double getComplementoCategoria() {
        return this.complementoCategoria;
    }
    
    public void setComplementoCategoria(double complementoCategoria) {
        this.complementoCategoria = complementoCategoria;
    }
    public double getSalarioBaseCategoria() {
        return this.salarioBaseCategoria;
    }
    
    public void setSalarioBaseCategoria(double salarioBaseCategoria) {
        this.salarioBaseCategoria = salarioBaseCategoria;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public Set getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set trabajadors) {
        this.trabajadors = trabajadors;
    }




}


