package model;
// Generated 11-may-2023 20:51:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private Integer idEmpresa;
     private String nombre;
     private String cif;
     private Set trabajadors = new HashSet(0);

    public Empresas() {
    }

	
    public Empresas(String nombre, String cif) {
        this.nombre = nombre;
        this.cif = cif;
    }
    public Empresas(String nombre, String cif, Set trabajadors) {
       this.nombre = nombre;
       this.cif = cif;
       this.trabajadors = trabajadors;
    }
   
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }
    public Set getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set trabajadors) {
        this.trabajadors = trabajadors;
    }




}


